fix(ws): update JSON payload for listing workspaces
kubeflow/notebooks pull request #134
Opened 2024-11-26 22:11 UTC by mohamedch7

# Fix: Update Workspace Model and JSON Payload Structure

This PR addresses [issue #127](https://github.com/kubeflow/notebooks/issues/127) by refactoring the workspace model and adjusting the JSON payload structure to align with the updated API requirements.

## Changes Made
- **Workspace Model Updates**:
  - Introduced new fields: `WorkspaceKind`, `PodTemplate`, `Activity`, and `Volumes`.
  - Updated nested models (`PodMetadata`, `ImageConfig`, `PodConfig`) for improved modularity.

- **Handler Updates**:
  - Refactored test cases in `workspaces_handler_test.go` to validate the new model and payload structure.

- **Repository Adjustments**:
  - Updated the `CreateWorkspace` method in `workspaces.go` to reflect the new model structure.
  - Ensured compatibility with nested fields during workspace creation.

- **Payload Adjustments**:
  - Ensured responses match the updated API specification.

## Impact
- Aligns backend structure with updated API expectations.

## Testing
- Unit tests in `workspaces_handler_test.go` updated to include new cases.

2024-11-27 12:16 UTC, ederign commented
@mohamedch7 thank you so much for the contribution! I'll look it before end of the week.

2024-11-28 05:28 UTC, thesuperzapper commented
@mohamedch7 once we merge https://github.com/kubeflow/notebooks/pull/137 (hopefully tomorrow) please rebase this PR so you get the new linting (and make sure your PR passes a `make lint`).

2024-12-02 19:57 UTC, ederign requested changes
Hi @mohamedch7 thank you so much for the PR. I left some required changes for your PR.
Could you review all the fields according to:
https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/main/crds/workspace-kind.yaml
and https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/main/crds/workspace.yaml

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +			 Type: item.Spec.PodTemplate.Options.ImageConfig,
This should be POD_TEMPLATE.
https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/main/crds/workspace-kind.yaml#L51

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +				 Labels:      item.Spec.PodTemplate.PodMetadata.Labels,
We should avoid nulls on those fields.

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +				 Annotations: item.Spec.PodTemplate.PodMetadata.Annotations,
"labels": null,
          "annotations": null

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +					 PvcName:   item.Spec.PodTemplate.Volumes.Data[0].PVCName,
Home is not Volumes.Data[0], but instead defined by kind: 
the mount path is defined in the WorkspaceKind under
      ##    `spec.podTemplate.volumeMounts.home`

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +				 Data: dataVolumes,
Make sure to don't list 'home' here.

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +				 Desired:       item.Spec.PodTemplate.Options.PodConfig,
It should be:
  Pod Template Options:
    Image Config:
      Desired:  jupyterlab_scipy_190

2024-12-02 19:57 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +				 Desired:       item.Spec.PodTemplate.Options.PodConfig,
(on status)

2024-12-02 19:58 UTC, ederign commented
Also, make sure to rebase it to include the new linting etc.

2024-12-03 16:12 UTC, thesuperzapper commented
@mohamedch7 you should be able to rebase it to head of `notebooks-v2` now, and then make sure `make lint` and `make test` pass.

2024-12-05 00:13 UTC, mohamedch7 commented on workspaces/backend/internal/models/workspaces.go
> +				 Desired:       item.Spec.PodTemplate.Options.PodConfig,
@ederign  Can you please explain more ?

2024-12-18 21:18 UTC, akrem-chabchoub commented on workspaces/backend/internal/models/workspaces.go
> +			 Type: item.Spec.PodTemplate.Options.ImageConfig,
Resolved

2024-12-18 21:35 UTC, mohamedch7 commented on workspaces/backend/internal/models/workspaces.go
> +				 Labels:      item.Spec.PodTemplate.PodMetadata.Labels,
Resolved

2024-12-18 22:04 UTC, mohamedch7 commented on workspaces/backend/internal/models/workspaces.go
> +					 PvcName:   item.Spec.PodTemplate.Volumes.Data[0].PVCName,
Should fetch WorkspaceKind then use it, right ?

2024-12-19 12:13 UTC, mohamedch7 commented on workspaces/backend/internal/models/workspaces.go
> +				 Desired:       item.Spec.PodTemplate.Options.PodConfig,
Resolved

2025-01-13 19:42 UTC, ederign requested changes
@mohamedch7 I'm sorry for the delay on this PR. I was in a long PTO but I'm back.

I just asked here a small changes. I'll review as soon as you send the PR. And please, don't forget to sign the commits.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace1),
Our model should only be responsible for translate k8s object for our DTOs/pojos. We should not add any extra logic there. Could you please pass the kind as a parameter?

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace2),
same as above

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace3),
same as above

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace1),
same as above.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace2),
same as above.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +func NewWorkspaceModelFromWorkspace(ctx context.Context, cl client.Client, item *kubefloworgv1beta1.Workspace) WorkspaceModel {
As described above, we should pass only the kind as parameter and don't leak the client.

Also, when you fetch the kind, if it does return an error, we should not return an empty kind, but fail and return err.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/models/workspaces.go
> +	wsk := &kubefloworgv1beta1.WorkspaceKind{}
move this lines to repository.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/repositories/workspaces.go
> +		workspaceModel := models.NewWorkspaceModelFromWorkspace(ctx, r.client, &item)
same as others.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/repositories/workspaces.go
> +	workspaceModel := models.NewWorkspaceModelFromWorkspace(ctx, r.client, workspace)
same as others.

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/repositories/workspaces.go
>  			// TODO: the pod and workspace labels should be separated
Can you please remove my old TODO here?

2025-01-13 19:42 UTC, ederign commented on workspaces/backend/internal/repositories/workspaces.go
> +	return models.NewWorkspaceModelFromWorkspace(ctx, r.client, workspace), nil
same as others.

2025-01-15 20:30 UTC, mohamedch7 commented on workspaces/backend/api/workspaces_handler_test.go
> +				models.NewWorkspaceModelFromWorkspace(ctx, k8sClient, workspace1),
Ok

2025-01-19 12:15 UTC, yehudit1987 commented
Hi @mohamedch7, please, don't forget to sign the commits, you have 8 unsigned commits.

2025-01-22 15:43 UTC, ederign approved these changes

2025-01-22 16:05 UTC, ederign commented
@mohamedch7, can you please sign the commit?

2025-01-24 21:11 UTC, thesuperzapper approved these changes
In the interest of moving this forward, I will approve.

There is one big issue I found (see comments) but other than that I expect we will be rewriting a lot of this anyway, so its good to have a base to work from.

2025-01-24 21:11 UTC, thesuperzapper commented on workspaces/backend/internal/repositories/workspaces.go
> +		if err := r.client.Get(ctx, client.ObjectKey{Name: item.Spec.Kind}, kind); err != nil {
It's not guaranteed that a WorkspaceKind will actually exist, even if it has been referenced by a Workspace (things can happen which bypass the validation webhook).

So in a follow-up PR, we need to gracefully handle Workspaces with missing WorkspaceKinds (e.g. still list them but indicate that we can't fully process them).

2025-01-24 21:11 UTC, thesuperzapper commented on workspaces/backend/internal/repositories/workspaces.go
> +		if err := r.client.Get(ctx, client.ObjectKey{Name: item.Spec.Kind}, kind); err != nil {
Same idea here, WSK might be missing.

2025-01-24 21:11 UTC, thesuperzapper commented on workspaces/backend/internal/repositories/workspaces.go
> +	if err := r.client.Get(ctx, client.ObjectKey{Name: workspace.Spec.Kind}, kind); err != nil {
Same idea here, WSK might be missing.

2025-01-24 21:11 UTC, thesuperzapper commented on workspaces/backend/internal/repositories/workspaces.go
> +	if err := r.client.Get(ctx, client.ObjectKey{Name: workspace.Spec.Kind}, kind); err != nil {
Same idea here, WSK might be missing.

2025-01-24 21:42 UTC, thesuperzapper commented
/lgtm

2025-01-24 21:43 UTC, merged