chore: update go linting + update dependencies for controller
kubeflow/notebooks pull request #137
Opened 2024-11-28 05:15 UTC by thesuperzapper

This PR makes the following changes:

1. Updates to dependencies used on the controller:

      - Go 1.21 -> 1.22
      - controller-runtime: 0.17.3 -> 0.19.1
      - golangci-lint: 1.57.2 -> 1.61.0
      - EnvTest: 1.29 -> 1.31

2. Updates to dependencies used by backend:

      - controller-runtime: 0.17.3 -> 0.19.1
      - golangci-lint: 1.57.2 -> 1.61.0
      - EnvTest: 1.29 -> 1.31

3. Improved the linting for all go projects (controller, backend):

     - We now enforce comment formats
     - We now enforce license headers
     - We now do lots of code smell checks
     - We now have a spell checker

2024-11-28 05:27 UTC, thesuperzapper commented
@ederign can you please LGTM when you are ready, this is an important update, and we need to get other PRs to rebase on it so they get the new linting.

/approve

2024-12-02 12:59 UTC, ederign requested changes
@thesuperzapper thank you so much for this important PR. Just want to double check a few things before +1.

2024-12-02 12:59 UTC, ederign commented on workspaces/controller/internal/webhook/workspacekind_webhook_test.go
> -			tc := tc // Create a new instance of tc to avoid capturing the loop variable.
@thesuperzapper I want to double-check with you that this doesn't break anything. Based on the comment, the variable looks pretty intentional :)

2024-12-02 12:59 UTC, ederign commented on workspaces/controller/config/rbac/role.yaml
> -- apiGroups:
Also, are sure about changing the roles?

2024-12-02 12:59 UTC, ederign commented on workspaces/controller/config/rbac/role.yaml
> -- apiGroups:
(just to verify that this is not something automatically added).

2024-12-02 16:48 UTC, thesuperzapper commented on workspaces/controller/internal/webhook/workspacekind_webhook_test.go
> -			tc := tc // Create a new instance of tc to avoid capturing the loop variable.
It's no longer necessary to copy variables in the loop because go 1.22 fixed the issue. 

It's actually a thing required by the linter now, because it would be wasteful to copy it twice.

2024-12-02 16:49 UTC, thesuperzapper commented on workspaces/controller/config/rbac/role.yaml
> -- apiGroups:
This is automatically generated, I think it just re-ordered them.

2024-12-02 16:56 UTC, ederign approved these changes

2024-12-02 16:56 UTC, ederign commented
/lgtm

2024-12-02 16:56 UTC, merged