feat (ws): Backend Kubernetes client #12
kubeflow/notebooks pull request #15
Opened 2024-06-05 14:07 UTC by ederign

- Creation of Kubernetes Client
- Wrapping the client on application

2024-06-05 14:15 UTC, ederign commented
FYI: I just signed the CLA.

@thesuperzapper thank you so much for the help and guidance on this one.

2024-06-05 21:16 UTC, thesuperzapper commented
/check-cla

2024-06-05 21:22 UTC, thesuperzapper commented
@ederign you might need to force push so the bot rechecks

2024-06-05 22:04 UTC, ederign commented
@thesuperzapper done!

2024-06-06 04:29 UTC, thesuperzapper requested changes

2024-06-06 04:29 UTC, thesuperzapper commented on workspaces/backend/cmd/main.go
> +		logger.Error(err.Error())
This should probably exit with non-zero code rather than continuing.

```suggestion
		logger.Error(err.Error())
		os.Exit(1)
```

2024-06-06 04:29 UTC, thesuperzapper commented on workspaces/backend/Dockerfile
> +COPY integrations/ integrations/
It seems a bit strange to not just copy the entire source folder.

Especially since we are using a build stage, so there is no additional size added to the final container.

If you are worried about copying stuff, just add a `.dockerignore` as we have for the controller:
- https://github.com/kubeflow/notebooks/blob/notebooks-v2/workspaces/controller/.dockerignore

2024-06-06 21:06 UTC, ederign commented on workspaces/backend/cmd/main.go
> +		logger.Error(err.Error())
Yeah that was a mistake.

2024-06-06 21:09 UTC, ederign commented on workspaces/backend/Dockerfile
> +COPY integrations/ integrations/
Agree. I just tried to follow the same pattern of here: https://github.com/kubeflow/notebooks/blob/notebooks-v2/workspaces/controller/Dockerfile#L15-L17

Works for me in both ways.

2024-06-06 21:09 UTC, ederign commented on workspaces/backend/Dockerfile
> +COPY integrations/ integrations/
I've also added docker ignore file just in case.

2024-06-08 19:24 UTC, thesuperzapper commented
@ederign thanks, lets move forward so we can use this in the next PR.

/approve
/lgtm

2024-06-08 19:25 UTC, merged