Namespace UI
kubeflow/notebooks pull request #154
Opened 2024-12-05 07:53 UTC by YosiElias

![image](https://github.com/user-attachments/assets/e0dbcec3-2401-42a7-ac9e-082582f419f2)
![image](https://github.com/user-attachments/assets/0a63f929-eccf-4a78-a8ed-234eed732a70)

2024-12-05 21:50 UTC, paulovmr requested changes
Hi @YosiElias , thanks for the PR! I added a few comments inline, and I would like to ask you a few things to align this PR with the Kubeflow contributing guide and to make the review easier:
* I can see a few extra commits in this PR's branch, please consider adding just the one related to your changes, with your sign-off.
* To follow the commit naming convention, please consider having the text "`feat(ws): Notebooks 2.0 // Frontend // Namespace selector`" for the commit message and PR label.

Also please consider adding some Cypress tests to automate the namespace changing verification. Thanks!

2024-12-05 21:50 UTC, paulovmr commented on workspaces/frontend/src/app/DropDwon.tsx
> +import React, {
There is a typo in the filename, and I believe would be better to give it a more contextual name, like `NamespaceSelector.tsx`.

2024-12-05 21:50 UTC, paulovmr commented on workspaces/frontend/src/app/DropDwon.tsx
> +const NamespaceDropdown: FC = () => {
Same for the component name, consider changing it to `NamespaceSelector`.

2024-12-05 21:50 UTC, paulovmr commented on workspaces/frontend/src/app/hooks/useMount.tsx
> +const useMount = (callback:()=>void): void => {
IMHO, the `useEffect` could be used directly, without this hook.

2024-12-05 21:50 UTC, paulovmr commented on workspaces/frontend/src/app/DropDwon.tsx
> +      <select value={selectedNamespace} onChange={handleSelectChange}>
We should always try to use Patternfly 6 components when available/applicable. In this case, this [context selector example](https://www.patternfly.org/components/menus/context-selector) would work extremely well.

2024-12-10 10:52 UTC, asaadbalum commented on workspaces/frontend/src/app/hooks/useMount.tsx
> +const useMount = (callback:()=>void): void => {
It is a preparation for future useEffect calls without dependencies, meaning, it's much for "readable" and compact this way in our opinion (one line simple call wrapping a function, instead of whole useEffect syntax)
If you still think a direct useEffect call is better, we will refactor it back.

2024-12-11 15:33 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/NamespaceSelector.tsx
> +    </div>
We don't need this `<div>` wrapper
```suggestion
      <Dropdown
        onSelect={onSelect}
        toggle={(toggleRef) => (
          <MenuToggle
            ref={toggleRef}
            onClick={() => setIsOpen(!isOpen)}
            isExpanded={isOpen}
            className="namespace-select-toggle"
          >
            {selectedNamespace}
          </MenuToggle>
        )}
        isOpen={isOpen}
      >
        <DropdownList>{dropdownItems} </DropdownList>
      </Dropdown>
```

2024-12-11 15:33 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/NamespaceSelector.css
> +}
I personally wouldn't add these styles. We should leave components to their default styling based on Patternfly and once we get further along in development we can enhance the UI look based on @jenny-s51 contributions.

2024-12-11 15:33 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/NamespaceSelector.tsx
> +const NamespaceSelector: FC = () => {
Can we put this component in a new folder called `components`. This will be easier for us to manage the repo going forward since we will be adding lots of custom components.

2024-12-16 14:22 UTC, YosiElias commented on workspaces/frontend/src/app/NamespaceSelector.tsx
> +    </div>
You're absolutely right, thanks

2024-12-16 14:25 UTC, YosiElias commented on workspaces/frontend/src/app/NamespaceSelector.css
> +}
Got it, I took that out

2024-12-16 14:31 UTC, YosiElias commented on workspaces/frontend/src/app/NamespaceSelector.tsx
> +const NamespaceSelector: FC = () => {
I added the new folder under 'shared' to be align with the model-registry structure

2024-12-17 16:54 UTC, Griffin-Sullivan reviewed
If you make the changes I suggested, you can then run the following in the `frontend/` dir:

`npm run test:fix`

and that should fix your CI failure.

2024-12-17 16:54 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
> +export const useNamespaceContext = () => {
```suggestion
export const useNamespaceContext = (): NamespaceContextState => {
```

2024-12-17 16:54 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/hooks/useMount.tsx
> +      }, []);
```suggestion
      });
```

2024-12-18 14:41 UTC, paulovmr commented on workspaces/frontend/src/shared/components/NamespaceSelector.tsx
> +    <Dropdown
@YosiElias Apart from the "Dropdown" usage, I believe the `<MenuSearch>` in that Patternfly [context selector example](https://www.patternfly.org/components/menus/context-selector) would work well here. @jenny-s51 wdyt?

2024-12-18 16:54 UTC, jenny-s51 commented on workspaces/frontend/src/shared/components/NamespaceSelector.tsx
> +    <Dropdown
Yes @paulovmr using <MenuSearch> how it is used in the Patternfly [context selector example](https://www.patternfly.org/components/menus/context-selector) would indeed work well here

2024-12-19 08:32 UTC, YosiElias commented on workspaces/frontend/src/app/hooks/useMount.tsx
> +      }, []);
@Griffin-Sullivan thanks for you comments!
I have a question, why would you want to remove the dependencies array? 
If we do that, it’ll run after every render (and re-render), but we only want it to run on the first render, don’t we? (that was the intention of useMount)

2024-12-22 14:30 UTC, YosiElias commented on workspaces/frontend/src/shared/components/NamespaceSelector.tsx
> +    <Dropdown
Done:
![image](https://github.com/user-attachments/assets/a15d4890-fb20-4f36-859b-8235f22ce19c)

2024-12-29 15:04 UTC, YosiElias commented
Please note that, to unblock others, #167 needs to be merged before this PR.

2025-01-08 18:39 UTC, Griffin-Sullivan commented on workspaces/frontend/src/app/hooks/useMount.tsx
> +      }, []);
ok looks like you added the correct dependency instead. I was only telling you what to do so you could get past the tests. Leave it as is for now.

2025-01-08 18:41 UTC, Griffin-Sullivan approved these changes
I think it looks good nice work!

2025-01-08 19:16 UTC, paulovmr requested changes
Thanks @YosiElias , just a few small comments, otherwise LGTM!

2025-01-08 19:16 UTC, paulovmr commented on workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/NamespaceSelector.cy.ts
> +    cy.get('[data-testid="namespace-toggle"]').click();
Please consider using `cy.findByTestId('namespace-toggle')` instead of `cy.get('[data-testid="namespace-toggle"]')`, for the other lines as well.

2025-01-08 19:16 UTC, paulovmr commented on workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
> +export const NamespaceProvider: React.FC<NamespaceProviderProps> = ({ children }) => {
Please consider renaming this to keep it consistent with model registry suffixes.
```suggestion
export const NamespaceContextProvider: React.FC<NamespaceProviderProps> = ({ children }) => {
```

2025-01-08 19:16 UTC, paulovmr commented on workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
> +interface NamespaceContextState {
Please consider renaming this to keep it consistent with model registry suffixes.
```suggestion
interface NamespaceContextType {
```

2025-01-09 07:33 UTC, YosiElias commented
Thank you @paulovmr and @Griffin-Sullivan for the comments!
Everything is fixed and ready to merge.

2025-01-09 12:05 UTC, paulovmr approved these changes

2025-01-09 13:25 UTC, ederign approved these changes

2025-01-09 13:25 UTC, ederign commented
/lgtm

2025-01-09 13:26 UTC, ederign commented
Thank you for the PR @YosiElias !

2025-01-09 13:26 UTC, merged