Fix for RHOAIENG-16233: Notebooks-v2 Filter workspaces
kubeflow/notebooks pull request #157
Opened 2024-12-11 17:33 UTC by ElayAharoni

Fixes #143.

extracted filtering logic into different generic Filter component.

implemented logic for filtering with single filter and multiple filters, including adding and removing.

cleaned the workspaces file code a little bit with inserting looping over data.

added cypress tests for the filtering.
made minor change in the cypress.config file in order to be able to see changes in the ui immidiatly on the cypress gui and make testing more easy, so we dont need to do build on each change in order to see it on cypress.

2025-01-14 02:43 UTC, paulovmr requested changes

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/workspaces/filterWorkspacesTest.cy.ts
> +const useFilter = (filterName: string, searchValue: string) => {
Why were these tests duplicated in two different folders?

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +export interface FilterProps {
This object is not a domain type, it is more related to the Filter component, thus it would be better to have it exported in the `Filter.tsx` file.

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +export interface FilterObj {
This object is not a domain type, it is more related to the Filter component, thus it would be better to have it in the `Filter.tsx` file.

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +export interface FilterObj {
```suggestion
export interface FilteredColumn {
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +  filterName: string;
```suggestion
  columnName: string;
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +  const FilterMenuToggle = React.useMemo(
```suggestion
  const filterMenuToggle = React.useMemo(
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +      filter.filterName === activeFilter.filterName && setSearchValue('');
```suggestion
      if (filter.filterName === activeFilter.filterName) {
        setSearchValue('');
      }
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +      index === -1 ? setSearchValue('') : setSearchValue(filters[index].value);
```suggestion
      setSearchValue(index === -1 ? '' : filters[index].value);
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +      setActiveFilter({ filterName: itemId, value: searchValue });
```suggestion
      setActiveFilter({
        filterName: itemId ? itemId.toString() : Object.values(columnNames)[0],
        value: searchValue,
      });
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +    [filters, isFilterMenuOpen, searchValue],
```suggestion
    [filters, isFilterMenuOpen, searchValue, columnNames],
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/shared/components/Filter.tsx
> +          Create Workspace
These button can't be defined here as this is a re-usable component.

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +          case 'Name':
These `case`s can now use the `columnNames` instead of the name itself.

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +          case 'CPU':
CPU and memory should not be filterable columns.

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +      // eslint-disable-next-line array-callback-return
```suggestion
```

2025-01-14 02:43 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +          default:
```suggestion
          default:
            return false;
```

2025-01-14 08:46 UTC, ElayAharoni commented on workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/workspaces/filterWorkspacesTest.cy.ts
> +const useFilter = (filterName: string, searchValue: string) => {
so they will run when testing on local and on pushing to github.
maybe there is better way to do so, i would like suggestions

2025-01-20 12:35 UTC, paulovmr approved these changes
Thanks, @ElayAharoni !

2025-01-20 13:23 UTC, ederign approved these changes

2025-01-20 13:23 UTC, ederign commented
/lgtm

2025-01-20 13:26 UTC, merged