feat(ws): Add popup to Workspace data vol column in workspaces table
kubeflow/notebooks pull request #160
Opened 2024-12-12 15:14 UTC by ElayAharoni

Fixes: #149

added popup with the worspace data vol info, that will show when hovering on the data vol column field.

please inform me if anything needs to be changes in matter of functionality or styling.

added a picture of the change:

![image](https://github.com/user-attachments/assets/a347b2e9-67cf-4c08-982e-a8ea67485c53)

2024-12-16 16:49 UTC, paulovmr commented
Hi @ElayAharoni , thanks for the PR! For this task, I asked Eugenia from UX to give her input on the best component to use to show those data volumes. One thing that would need to change, is that we need to show not only the first but all elements from the `workspace.podTemplate.volumes.data` array, so there might be a need for an alternative component than the `Popover`.

2024-12-16 16:49 UTC, paulovmr reviewed
Hi @ElayAharoni , thanks for the PR! For this task, I asked @jenny-s51 from UX to give her input on the best component to use to show those data volumes. One thing that would need to change, is that we need to show not only the first but all elements from the `workspace.podTemplate.volumes.data` array, so there might be a need for an alternative component than the `Popover`.

2024-12-16 22:18 UTC, ElayAharoni commented
Hi Paulo, thanks for your comment.

I think that if we need to show larger data than what is shown right now, then maybe it will be better not to show it when hovering on the field. 
But to show it when clicking on the helpIcon that next to it, and then we can open a dialog or other component with all the relevant data.

Please let me know what you think about it.

2024-12-17 14:09 UTC, paulovmr commented
Hi @jenny-s51 , here is the PR about the data volumes column.

2024-12-17 14:53 UTC, jenny-s51 commented
Hi @paulovmr , thank you for tagging me! https://github.com/kubeflow/notebooks/issues/150 is a similar ticket as well. Per our recent conversation this morning we agreed that the expandable table variant is an effective approach and component to use for these cases - since we want to show additional data for multiple columns in this table view, using the PF[ expandable table variant](https://www.patternfly.org/components/table/react-demos#expandcollapse-all) offers more flexibility and provides a visual cue to the user that there is more data within the table view. WDYT @ElayAharoni ?

2024-12-17 15:23 UTC, ElayAharoni commented
I think it will be the best approach, as it is a solution for all the columns that need to show additional data.
And it is also the way it is implemented in the ODH.

Do you want me to implement it in my pr and then all the other relevant PR's will be based on mine? 
@paulovmr , @jenny-s51

2024-12-17 15:43 UTC, jenny-s51 commented
Yes, that sounds like a good plan, @ElayAharoni.

2024-12-18 09:31 UTC, ElayAharoni commented
hi @paulovmr , @jenny-s51.
i have made the changes, to show the data via expendable table row.
attached screenshot for reference:

![image](https://github.com/user-attachments/assets/ca815c9d-284c-43a1-ba12-6abce999fe52)

2024-12-18 17:13 UTC, paulovmr commented
IMO the idea of adding a expandable row would eliminate the need for a normal column for that field, since the expandable part would be presented as a separate row that adds more information, and not an extension to the columns, like seen in [here](https://www.patternfly.org/components/table#expandable). @jenny-s51 do you agree?

2024-12-18 22:50 UTC, jenny-s51 reviewed
This is a good callout @paulovmr - if we are showing additional data for multiple columns, the data should be presented within the span of the column it is associated with. 

Here is a good example of how this is currently done in the RHOAI Dashboard, for example the "Container size" column has Limits and Memory within the same column span (see [NotebookTableRow.tsx](https://github.com/jenny-s51/odh-dashboard/blob/main/frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx#L218-L243)).
<img width="400" alt="Screenshot 2024-12-18 at 5 22 17 PM" src="https://github.com/user-attachments/assets/5d7b6be8-c9e3-44c3-bf3d-6b3856d7cfca" />

We also want to make sure to wrap the content of each child row cell in ExpandableRowContent to apply the correct styles. @ElayAharoni

2024-12-19 11:08 UTC, ElayAharoni commented
hi @jenny-s51 @paulovmr.
i have made the requested fixes.
attached new snapshot:
![image](https://github.com/user-attachments/assets/19aa341a-0375-4f14-a5d9-67da6423c2af)

2024-12-22 08:45 UTC, ElayAharoni commented
hi @paulovmr , @jenny-s51.
after the discussions we had this is the current fix.
please review when you have time.
attached latest snapshot: 
![image](https://github.com/user-attachments/assets/5f246a50-9610-4864-9eef-35b8f93b8ce4)

2025-01-09 13:59 UTC, paulovmr requested changes

2025-01-09 13:59 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/ExpandedDataVol.tsx
> +      <Content component="h3">Data Volumes:</Content>
@ElayAharoni IMO the List component from PatternFly might be a better fit for this kind of information on the UI. Please consider replacing the `Content` usage for the `List` component.

2025-01-09 13:59 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/ExpandedDataVol.tsx
> +          <div>
In general, it is best to avoid the usage of plain HTML components in the middle of PatternFly components to avoid breaking future CSS rules.

2025-01-09 13:59 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/ExpandedDataVol.tsx
> +export const ExpandedDataVol: React.FC<ExpandedDataVolProps> = ({ workspace }) => {
Please consider renaming this component (and also other associated declarations).
```suggestion
export const DataVolumesList: React.FC<ExpandedDataVolProps> = ({ workspace }) => {
```

2025-01-09 14:01 UTC, ElayAharoni commented
@paulovmr thanks for your comments i will fix them

2025-01-09 16:30 UTC, paulovmr requested changes
Hi @ElayAharoni , left a few minor changes inline. One thing that is important as well is to remove the `Data Vol` column from the table, now that the information has moved to the expandable row. Also please add the new type `WorkspacesColumnNames` to the variable `columnNames`.

2025-01-09 16:30 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/DataVolumesList.tsx
> +interface ExpandedDataVolProps {
```suggestion
interface DataVolumesListProps {
```

2025-01-09 16:30 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/DataVolumesList.tsx
> +export const DataVolumesList: React.FC<ExpandedDataVolProps> = ({ workspace }) => {
```suggestion
export const DataVolumesList: React.FC<DataVolumesListProps> = ({ workspace }) => {
```

2025-01-09 17:53 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +            <Th sort={getSortParams(6)}>{columnNames.lastActivity}</Th>
I believe there was an issue with the conflict resolution here, because the `lastActivity` column is duplicated. Also, because the Data Vol column was removed, it has to also be removed from the sortable rows, and the parameters to the getSortParams should be changed too.

2025-01-12 08:57 UTC, ElayAharoni commented on workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
> +            <Th sort={getSortParams(6)}>{columnNames.lastActivity}</Th>
yeah you are right, i have fixed and pused for the final time i hope

2025-01-13 12:54 UTC, paulovmr approved these changes

2025-01-13 13:02 UTC, ederign approved these changes

2025-01-13 13:02 UTC, ederign commented
/lgtm

2025-01-13 13:03 UTC, merged