feat(ws): Add "Connect" column to workspace table and display popup with workspace endpoints.
kubeflow/notebooks pull request #161
Opened 2024-12-17 07:42 UTC by Yael-F

Fixes #150 
This PR adds a "Connect" column to the workspace table, positioned before the Actions column. 
The new column displays a list of endpoints on hover.

I've added a screenshot of the implementation. Please let me know if any further changes are needed.
![image](https://github.com/user-attachments/assets/5820a954-a020-4805-a342-1fd0fedd9e6b)

2025-01-14 17:46 UTC, Yael-F commented
Following a discussion with @jenny-s51, we've decided to move the endpoints into the expanded table row. 

The updated screenshot:
![image](https://github.com/user-attachments/assets/eafd87d2-0c97-4fdb-a478-0585b819571f)

2025-01-15 03:07 UTC, thesuperzapper commented
@Yael-F The intention of this button is to connect to the notebook instance (open a new tab), making it the single most important button on the page, it __must__ be in the main row.

The design I was thinking was a button with dropdown to select which port to connect to.

![gAt78](https://github.com/user-attachments/assets/9419a270-5ef9-4a34-8afe-3230404e635a)

__NOTE:__ replace "Primary" with "Jupyter" (or whatever the first port is called), and the other actions being the other ports (or greyed out if there is only one).

__NOTE 2:__ we might also want some kind of "connect" icon on the left side of the button, but I am not sure if that will just clutter.

2025-01-15 14:22 UTC, ederign commented
@Yael-F I agree with @thesuperzapper! That is the primary action when I open the workspaces listing.

2025-01-23 21:01 UTC, Yael-F commented
Hey @thesuperzapper 
Moved the connect button to the main row, if you can take a look.

![image](https://github.com/user-attachments/assets/5f6904b1-fa56-4918-afb3-5e44d9db6347)

Jenn (the UX) suggested to label the dropdown with "Connect" (instead of the first endpoint) for better clarity, what do you say?

2025-02-03 21:26 UTC, paulovmr requested changes
Hi @Yael-F , thanks for the PR! 
Please check the `npm run test` locally, it has a few errors. You can use `npm run test:fix` to fix most of them. Also please rebase your branch with the latest commits.

2025-02-03 21:26 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/WorkspaceEndpoints.tsx
> +export const EndpointsDropdown: React.FunctionComponent<EndpointsDropdownProps> = ({workspace}) => {
Please consider renaming the file and component (and other associated types, like the `EndpointsDropdownProps`) to `WorkspaceConnectAction`.

2025-02-04 16:03 UTC, paulovmr approved these changes

2025-02-04 16:10 UTC, ederign approved these changes

2025-02-04 16:10 UTC, ederign commented
/lgtm

2025-02-04 16:11 UTC, merged