feat(ws): Implement Start restart and stop workspace actions
kubeflow/notebooks pull request #162
Opened 2024-12-18 14:41 UTC by ElayAharoni

Fixes: #146

Implemented Start, restart and stop workspace actions present in the workspace table actions kebab dropdown.
with the requested buttons and warning, from the issue description.
snapshots:
1. start with pending updates: 
![image](https://github.com/user-attachments/assets/2a33d2bd-5d59-4b9a-93b7-5dadf31b074a)

2. restart without pending updates: 
![image](https://github.com/user-attachments/assets/d0a5b0ed-d5dc-46a4-ab68-663f119f2a0e)

3. stop without pending updates: 
![image](https://github.com/user-attachments/assets/a1c08f49-79df-4577-8433-0cd15895e1cb)

4. stop with pending updates: 
![image](https://github.com/user-attachments/assets/8cba5e30-fdbe-4a5b-afe6-3ed5291bb138)

5. restart with pending updates: 
![image](https://github.com/user-attachments/assets/4467030f-8923-4dac-a188-de6328e28a4e)

2025-01-06 11:41 UTC, paulovmr requested changes
Hi @ElayAharoni , thanks for the PR. IMO, we should have one component (and its `.tsx` file) for each of those modals, instead of managing UI features as React states. This way each component would be isolated and could call the appropriate BFF service to execute its action. In the `Workspaces.tsx`, we would have only the `const [isXModalOpen, setIsXModalOpen] = React.useState(false);` boolean state to manage if each popup is opened or not.

This idea is similar to what Model Registry does with `ModelVersionsTableRow` using the `ArchiveModelVersionModal` modal.

2025-01-30 14:17 UTC, ElayAharoni commented
i have made changes according to @thesuperzapper requests.
also this is the change after rebasing the latest changes.
https://www.loom.com/share/50623d12b176400e9d9ef1c0189b2afa

2025-02-05 14:12 UTC, ElayAharoni commented
hi @paulovmr i did the requested changes

2025-02-05 16:40 UTC, paulovmr requested changes
Thanks @ElayAharoni , the components modularity looks good to me now! I've left a few comments inline, and I have a few suggestions regarding some naming:
* Consider renaming `RestartActionAlert` to `WorkspaceRestartActionModal` (and similarly to the others)
* Consider renaming `ActionWithUpdatesBody` to `WorkspaceRedirectInformationView`
* Consider changing the `activeActionData` state to be only a `enum` with the type of the action. The already existing `selectedWorkspace` state could be used to hold the workspace and passed to the modal directly. Also please consider renaming it to `activeActionType`.

2025-02-05 16:40 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/ActionWithUpdatesBody.tsx
> +        There are pending redirect updates for that workspace, are you sure you want to proceed?
This text should be managed by each modal, outside this component.

2025-02-05 16:40 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/StartActionAlert.tsx
> +        <Button onClick={() => handleClick(true)}>Update and Start</Button>
There should be a condition to show this button, similar to the other modals.

2025-02-05 16:40 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +export interface AlertModalContent {
This type is not part of the domain, please consider moving it inside the `AlertModal.tsx` file.

2025-02-05 16:40 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/StopActionAlert.tsx
> +          <div>are you sure you want to Stop the workspace?</div>
Please consider using the `<Content component={ContentVariants.p}>` Patternfly component instead of the `div` here.

2025-02-06 08:55 UTC, ElayAharoni commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/StartActionAlert.tsx
> +        <Button onClick={() => handleClick(true)}>Update and Start</Button>
in the start action the modal will be shown only if the are pending updates and if not the start action will be invoked without the modal at all

2025-02-06 09:51 UTC, ElayAharoni commented
/rerun

2025-02-06 09:51 UTC, ElayAharoni commented
/rerun-all

2025-02-06 15:23 UTC, paulovmr requested changes

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRestartActionModal.tsx
> +              There are pending redirect updates for that workspace, Are you sure you want to
```suggestion
              There are pending redirect updates for that workspace. Are you sure you want to
```

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRestartActionModal.tsx
> +          <Content>Are you sure you want to Restart the workspace?</Content>
```suggestion
          <Content>Are you sure you want to restart the workspace?</Content>
```

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
> +          There are pending redirect updates for that workspace, are you sure you want to proceed?
```suggestion
          There are pending redirect updates for that workspace. Are you sure you want to proceed?
```

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
> +              There are pending redirect updates for that workspace, Are you sure you want to
```suggestion
              There are pending redirect updates for that workspace. Are you sure you want to
```

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
> +          <Content>Are you sure you want to Stop the workspace?</Content>
```suggestion
          <Content>Are you sure you want to stop the workspace?</Content>
```

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/shared/components/AlertModal.tsx
> +import React from 'react';
This file is not used anymore, please consider deleting it.

2025-02-06 15:23 UTC, paulovmr commented on workspaces/frontend/src/shared/types.ts
> +export enum ActionType {
This type is not part of the domain, please consider moving it inside the `Workspaces.tsx` file.

2025-02-06 16:23 UTC, paulovmr requested changes

2025-02-06 16:23 UTC, paulovmr commented on workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
> +          There are pending redirect updates for that workspace. are you sure you want to proceed?
```suggestion
          There are pending redirect updates for that workspace. Are you sure you want to proceed?
```

2025-02-06 18:31 UTC, ederign approved these changes

2025-02-06 18:32 UTC, ederign commented
/lgtm

2025-02-06 18:32 UTC, merged