feat: client ui frontend scaffolding
kubeflow/notebooks pull request #19
Opened 2024-06-21 18:57 UTC by ederign

In this PR:
- UI frontend scaffolding
- Github Action for frontend and backend

## Description

Next week, we plan to start adding features to our frontend, so I've created a scaffolding PR with a basic project structure to avoid mixing it with feature development.

![image](https://github.com/kubeflow/notebooks/assets/531351/61b831fd-ea4b-4692-8e39-646691f00676)

## How Has This Been Tested?
 
 Run local dev mode and prod builds.

2024-06-21 19:23 UTC, jiridanek commented on .github/workflows/ui-bff-build.yml
> +          go-version: '1.22.2'
If you give it explicit path to go.sum, this can fetch and cache go dependencies for you. And you can tell it to take go version from your go.mod, so there is a little bit less duplicated information

https://github.com/kubeflow/notebooks/blob/notebooks-v2/.github/workflows/workspaces-controller_unit-tests.yaml#L20-L25

2024-06-21 19:54 UTC, ederign commented on .github/workflows/ui-bff-build.yml
> +          go-version: '1.22.2'
agree! I just updated it! Thanks for the tip!

2024-06-28 00:13 UTC, thesuperzapper requested changes

2024-06-28 00:13 UTC, thesuperzapper commented on .github/workflows/ui-bff-build.yml
> +      - '**.gitignore'
Lets do the same thing as we do for controller tests, and only run on PR when files under `workspaces/frontend` change.

https://github.com/kubeflow/notebooks/blob/3e89605c4d4d8adbb3c8de1d3cc5e4d8a851701e/.github/workflows/workspaces-controller_unit-tests.yaml#L9

I also dont think we need to ignore any specific files.

2024-06-28 00:13 UTC, thesuperzapper commented on .github/workflows/ui-frontend-build.yml
> +      - '**.gitignore'
Same as above.

2024-06-28 00:13 UTC, thesuperzapper commented on workspaces/frontend/README.md
> +The Kubeflow Workspaces Frontend is the web application used by the Kubeflow Workspaces as part of [Kubeflow Notebooks 2.0](https://github.com/kubeflow/kubeflow/issues/7156).
```suggestion
The Kubeflow Workspaces Frontend is the web user interface used to monitor and manage Kubeflow Workspaces as part of [Kubeflow Notebooks 2.0](https://github.com/kubeflow/kubeflow/issues/7156).
```

2024-06-28 00:13 UTC, thesuperzapper commented on workspaces/frontend/package.json
> +  "description": "The Kubeflow Workspaces Frontend is the web application used by the Kubeflow Workspaces as part of Kubeflow Notebooks 2.0",
```suggestion
  "description": "The Kubeflow Workspaces Frontend is the web user interface used to monitor and manage Kubeflow Workspaces as part of Kubeflow Notebooks 2.0",
```

2024-06-28 00:13 UTC, thesuperzapper commented on workspaces/frontend/src/app/routes.tsx
> +  },
We should name this just "Main" to not be confused with "Kubeflow Dashboard".

2024-06-28 00:13 UTC, thesuperzapper commented on workspaces/frontend/src/index.html
> +  <link href="/images/favicon.png" rel="icon" type="image/svg+xml">
This seems like a typo, because its claiming to be an SVG.

2024-06-28 00:13 UTC, thesuperzapper commented on workspaces/frontend/tsconfig.json
> +    "target": "es5",
Lets target `es6` like we do in Central Dashboard:

- https://github.com/kubeflow/kubeflow/blob/v1.8.0/components/centraldashboard/tsconfig.json#L5

2024-06-28 00:43 UTC, thesuperzapper approved these changes

2024-06-28 00:47 UTC, thesuperzapper commented
@ederign thanks for this, lets merge to keep wroking on the first features

/lgtm
/approve

2024-06-28 00:48 UTC, merged