add CONTRIBUTING.md, pull_request_template.md and ISSUE_TEMPLATE.
kubeflow/notebooks pull request #4
Opened 2024-05-09 12:55 UTC by ederign

To see this running:

issues:
https://github.com/ederign/notebooks/issues/new/choose 

PR:
<img width="838" alt="image" src="https://github.com/kubeflow/notebooks/assets/531351/820f9b9f-f9ad-4848-acf6-ed377f4f4f66">

2024-05-09 12:56 UTC, ederign commented
@thesuperzapper ^

2024-05-24 13:47 UTC, jiridanek requested changes

2024-05-24 13:47 UTC, jiridanek commented on CONTRIBUTING.md
> +__The name of your PR must be a semantic commit message__, with one of the following prefixes:
```suggestion
__The name of your PR must be a semantic commit message__, with one of the following _prefixes_ and one of the following _scopes_:
```

2024-05-24 13:47 UTC, jiridanek commented on CONTRIBUTING.md
> +
```suggestion
### Prefixes

```

2024-05-24 13:47 UTC, jiridanek commented on CONTRIBUTING.md
> +Please do NOT include a scope, as we do not use them, for example `feat(feature_name): my commit message`.
```suggestion
### Scopes

- `nb` (notebooks - web-app, controller, images)
- `pvc` (volumes - web-app, controller)
- `tb` (tensorboards - web-app, controller)
- `ws` (workspaces - frontend, backend, controller,, images)

For example `feat(ws): my commit message`.
````

2024-05-24 13:47 UTC, jiridanek commented on CONTRIBUTING.md
> +## Use Semantic Commits
This needs to include the info from 2024-05-08 8:00 AM PT meeting (https://docs.google.com/document/d/1SiWLah-U07hAc47sSsoI8-NkbkLnHl1YVzxw193QUKE/edit#heading=h.naudedl8te2q)

2024-05-24 13:47 UTC, jiridanek commented on CONTRIBUTING.md
> +This is my commit message
```suggestion
feat(ws): my commit message`
```

2024-05-24 13:49 UTC, jiridanek commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +      label: Kubernetes Distribution
Should we also have a field for Kubeflow distribution, or somehow handle users of Kubeflow distributions (https://www.kubeflow.org/docs/started/installing-kubeflow/#packaged-distributions-of-kubeflow) that come report to us?

2024-05-29 12:06 UTC, ederign commented
@jiridanek @thesuperzapper, can we merge this as a starting point?

2024-05-29 12:13 UTC, jiridanek commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +        Thanks for helping make the Kubeflow Notebooks project better!
```suggestion
        Thanks for helping to make the Kubeflow Notebooks project better!
```

2024-05-29 12:15 UTC, jiridanek commented on CONTRIBUTING.md
> +* shows you where to find the Contributor License Agreement (CLA) that you need
```suggestion
```

We have https://developercertificate.org/, not cla. Cla is evil.

2024-05-29 12:15 UTC, jiridanek commented on CONTRIBUTING.md
> +  to sign,
```suggestion
```

2024-05-29 12:19 UTC, jiridanek commented on CONTRIBUTING.md
> +* shows you where to find the Contributor License Agreement (CLA) that you need
@ederign btw, don't forget to sign commits ;P

2024-05-30 17:02 UTC, jiridanek approved these changes

2024-05-30 17:04 UTC, jiridanek commented on CONTRIBUTING.md
> +```
no new line at the end of file

2025-03-07 20:57 UTC, closed without merging