feat(nb): Initialize new kubebuilder controller in workspaces/controller
kubeflow/notebooks pull request #5
Opened 2024-05-13 11:48 UTC by jiridanek

```
cd workspaces/controller
go mod init github.com/kubeflow/notebooks/workspaces/controller
kubebuilder init \
    --plugins=go/v4 \
    --domain=kubeflow.org \
    --project-name=workspaces-controller \
    --repo=github.com/kubeflow/notebooks/workspaces/controller
kubebuilder create api --version v1beta1 --kind Workspace
kubebuilder create api --version v1beta1 --kind WorkspaceKind
make manifests
```

## TODO:
* [ ] integration test with kind (kubeflow/kubeflow notebooks controller has that)
* [ ] think about the branch patterns for GHA triggering (add release branches?)
* [ ] Translate the [current CRD spec](https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/tree/main/crds)

maybe something else from https://docs.google.com/document/d/1SiWLah-U07hAc47sSsoI8-NkbkLnHl1YVzxw193QUKE/edit#heading=h.naudedl8te2q

2024-05-13 19:17 UTC, thesuperzapper commented
@jiridanek I have made a new branch, which we can develop in (rather than `main`), please make your PR into: https://github.com/kubeflow/notebooks/tree/notebooks-v2

2024-05-23 17:13 UTC, thesuperzapper requested changes

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/.gitignore
> +*~
We dont need these, the root `.gitignore` is already doing them.

2024-05-23 17:13 UTC, thesuperzapper commented on .github/workflows/workspaces-controller_unit-tests.yaml
> +  workflow_dispatch:
We dont allow running actions.

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/README.md
> +# workspaces-controller
```suggestion
# Kubeflow Workspace Controller
```

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/README.md
> +limitations under the License.
```suggestion
```

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/README.md
> +// TODO(user): Add simple overview of use/purpose
```suggestion
The Kubeflow Workspace Controller is responsible for reconciling the `Workspace` and `WorkspaceKind` resources used in [Kubeflow Notebooks 2.0](https://github.com/kubeflow/kubeflow/issues/7156).

> ⚠️ __Warning__ ⚠️
>
> The Kubeflow Workspace Controller is a work in progress and is __NOT__ currently ready for use.
> We greatly appreciate any contributions. 

```

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/README.md
> +// TODO(user): An in-depth paragraph about your project and overview of use
```suggestion
```

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/cmd/main.go
> +		LeaderElectionID:       "7e934e16.kubeflow.org",
```suggestion
		LeaderElectionID:       "kubeflow-workspace-controller",
```

2024-05-23 17:13 UTC, thesuperzapper commented on workspaces/controller/config/default/kustomization.yaml
> +namespace: workspaces-controller-system
Lets re-init this folder with `workspace-controller` (no `"s"`)

2024-05-23 17:18 UTC, jiridanek commented on .github/workflows/workspaces-controller_unit-tests.yaml
> +  workflow_dispatch:
removed

2024-05-23 17:18 UTC, jiridanek commented on workspaces/controller/.gitignore
> +*~
removed

2024-05-23 17:22 UTC, jiridanek commented on workspaces/controller/config/default/kustomization.yaml
> +namespace: workspaces-controller-system
And use latest kubebuilder. And update go to 1.22 (latest).

2024-05-23 17:45 UTC, jiridanek commented on workspaces/controller/go.mod
> +	google.golang.org/protobuf v1.31.0 // indirect
there happens to be a cve against this protobuf version; I guess we can fix it with dependabot or something like that

2024-05-23 17:57 UTC, jiridanek commented on workspaces/controller/config/default/kustomization.yaml
> +namespace: workspaces-controller-system
renamed

the 1.22 in go.mod is not changed when I use latest kubebuilder and go 1.22 is installed on my machine, so I won't do anything about that

2024-05-23 18:32 UTC, thesuperzapper approved these changes

2024-05-23 18:36 UTC, thesuperzapper commented
/lgtm

2024-05-23 18:36 UTC, merged