feat(nb): Create Workspace and WorkspaceKind CRD definitions
kubeflow/notebooks pull request #6
Opened 2024-05-15 09:50 UTC by jiridanek

Followup on top of my
* https://github.com/kubeflow/notebooks/pull/5

2024-05-30 20:37 UTC, jiridanek commented on workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
> +                  imageConfig:
@thesuperzapper should this be `imageConfig` or `image`? Your spec has `image` here https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/176f31674aa559a69b24598765ac14825d7d3649/crds/workspace.yaml#L85

I presume that's just a mistake in your spec?

2024-05-30 20:38 UTC, jiridanek commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	LastActivity int64 `json:"lastActivity"`
I still need to learn how to do these validations. This one should not be too hard.

2024-05-30 20:40 UTC, jiridanek commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	// +kubebuilder:validation:XValidation:rule="has(self.url) && self.type == 'RequiredMember' ?  has(self.requiredMember) : !has(self.requiredMember)",message="requiredMember is required when type is
@thesuperzapper I spent a while trying to figure out how to specify that either `url` or `configMap` but not both may be specified here. I think the XValidation is the correct approach and I just need to learn how to write the rule expression.

2024-05-30 20:44 UTC, jiridanek commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	//  `virtualMachine` to run the Workspace on systems like KubeVirt/EC2 rather than in a Pod
so specifying both `podTemplate` and `virtualMachine` here at the same time will be an error?

2024-05-31 00:57 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	//  `virtualMachine` to run the Workspace on systems like KubeVirt/EC2 rather than in a Pod
In the future, yes, EXACTLY one of `podTemplate` or `virtualMachine` must be specified.

But we will only have `podTemplate` for a long while, so just mark that as required.

2024-06-06 00:42 UTC, thesuperzapper requested changes
@jiridanek I have made a large number of suggestions.

But the most important thing you need to do is regenerate the `WorkspaceKind` resource as a Cluster-Scoped resource, its currently Namespace-scoped.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Spawner Spawner `json:"spawner,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	PodTemplate WorkspaceKindPodTemplate `json:"podTemplate,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	//+kubebuilder:validation:Pattern:=^[a-z0-9][-a-z0-9]*[a-z0-9]$
This field does not need validation, its not used as the name of a resource.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +}
I haven't tested this, but I think this will be the correct validation to ensure exactly one of `url` and `configMap` is set:

```suggestion
// +kubebuilder:validation:XValidation:message="must specify exactly one of 'url' or 'configMap'",rule="!(has(self.url) && has(self.configMap)) && (has(self.url) || has(self.configMap))"
type WorkspaceKindIcon struct {
	//+kubebuilder:example="https://jupyter.org/assets/favicons/apple-touch-icon-152x152.png"
	//+kubebuilder:validation:Optional
	Url string `json:"url,omitempty"`

	//+kubebuilder:validation:Optional
	ConfigMap WorkspaceKindConfigMap `json:"configMap,omitempty"`
}
```

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Key string `json:"key,omitempty"`
These fields are required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	ServiceAccount ServiceAccount `json:"serviceAccount,omitempty"`
This is a required field, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	VolumeMounts VolumeMounts `json:"volumeMounts,omitempty"`
This is a required field, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	// +TODO kubebuilder:example=["bash", "-c", "exit 0"]
We can put full examples elsewhere, they don't need to be in the CRD spec, but this explains at least a little to users:

```suggestion
	// +kubebuilder:example=["bash", "-c", "exit 0"]
```

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Command []string `json:"command,omitempty"`
This is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	ActivityProbe WorkspaceKindActivityProbe `json:"activityProbe,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	LastActivity bool `json:"lastActivity,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	RequestHeaders []RequestHeader `json:"requestHeaders"`
This is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	ImageConfig ImageConfig `json:"ImageConfig"`
Should not be caps:
```suggestion
	ImageConfig ImageConfig `json:"imageConfig"`
```

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Redirect ImageConfigRedirect `json:"redirect"`
The `redirect` field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Hidden bool `json:"hidden"`
The `hidden` field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +type WorkspaceKindActivityProbe struct {
We should probably add a validation similar to the `WorkspaceKindIcon` one that requires exactly one of `exec` or `jupyter` to be set.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	ReadinessProbe *v1.Probe `json:"readinessProbe"`
These fields are all optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	RemovePathPrefix bool `json:"removePathPrefix"`
This is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	// todo example #set: { "X-RStudio-Root-Path": "{{ .PathPrefix }}" } # for RStudio
Either remove or finish this example.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Redirect PodConfigRedirect `json:"redirect"`
The `redirect` field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	DisplayName string `json:"display_name,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Description string `json:"description,omitempty"`
This field is required, remove `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +type PodConfigRedirect struct {
We can combine `PodConfigRedirect`  and `ImageConfigRedirect` into `OptionRedirect`, because they are the same.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	Paused bool `json:"paused"`
This field is optional, add `omitempty` and default=false.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	Data []PodVolumeMount `json:"data"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	Annotations map[string]string `json:"annotations"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	Labels map[string]string `json:"labels"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	PodMetadata PodMetadata `json:"podMetadata"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	LastActivity int64 `json:"lastActivity"`
Every integer is a valid unix epoch, so no need.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	DeprecationMessage string `json:"deprecationMessage"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Hidden bool `json:"hidden"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Deprecated bool `json:"deprecated"`
This field is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	//+kubebuilder:example:=false
This should default to false:
```suggestion
	//+kubebuilder:default:=false
```

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	WaitForRestart bool `json:"waitForRestart"`
This should default to true and be optional:

```suggestion
	//+kubebuilder:default:=true
	WaitForRestart bool `json:"waitForRestart,omitempty"`
```

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Affinity v1.Affinity `json:"affinity"`
This is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	NodeSelector v1.NodeSelector `json:"nodeSelector"`
This is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Tolerations []v1.Toleration `json:"tolerations"`
This is optional, add `omitempty`.

2024-06-06 00:42 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	Resources v1.ResourceRequirements `json:"resources"`
This is optional, add `omitempty`.

2024-06-06 14:59 UTC, jiridanek commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	LastActivity int64 `json:"lastActivity"`
No validation then, at least for now. I wanted this to be nonnegative.

Also, there's the `v1.time`, isn't it better to use that instead of timestamps?

2024-06-09 20:26 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspace_types.go
> +	LastActivity int64 `json:"lastActivity"`
@jiridanek negative is actually still a valid unix epoch, it just implies the number of seconds before `00:00:00 UTC on 1 January 1970`

2024-06-09 20:31 UTC, thesuperzapper commented on workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
> +                  imageConfig:
Yep, thanks, I have updated it to say `imageConfig`:

https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/5fbd45119f3d10f483b8c50a5de8a335ca0ef206/crds/workspace.yaml#L85

2024-06-09 20:32 UTC, thesuperzapper commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +	// +kubebuilder:validation:XValidation:rule="has(self.url) && self.type == 'RequiredMember' ?  has(self.requiredMember) : !has(self.requiredMember)",message="requiredMember is required when type is
See https://github.com/kubeflow/notebooks/pull/6#discussion_r1628564626 for my proposed `XValidation` schema.

2024-06-18 10:11 UTC, jiridanek commented on workspaces/controller/api/v1beta1/workspacekind_types.go
> +}
> Also, I just want to clarify, in what situations are you using pointers (*) in your type definitions, e.g. why are we using pointers for (I am forgetting when they are needed):

That's for the `has(self.exec)`. Pointers have the meaning of optionals in Go, and `nil` means that value is not present. I understand it might be helpful not to need it (1B $$$ and so on), but I did not manage to set up the `XValidation` without it.

The other occurrence of pointers in the PR is the same case, also XValidation.

2024-06-18 10:11 UTC, jiridanek commented
> @jiridanek I pushed a commit with some changes, I would appreciate you taking a look to see if I messed anything up: https://github.com/kubeflow/notebooks/commit/4dc0c160c6c32b66152f242569f20016ae42f4b0

looks good to me, thanks!

2024-06-19 01:00 UTC, thesuperzapper commented
@jiridanek I did some small updates in https://github.com/kubeflow/notebooks/pull/6/commits/bb2ca34414619e732e400e925960fc6979043b7b (mostly adding a few fields to the Workspace status that are needed for the UI), but I also added some configs to make the `kubectl get workspace` and `kubectl get workspacekind` more useful. 


I am going to merge this now, so we can start the reconciliation loop PR (we can make any further changes in that PR).

/lgtm
/approve

2024-06-19 01:00 UTC, merged