feat(nb): Scaffolding of backend(/workspaces/backend)
kubeflow/notebooks pull request #7
Opened 2024-05-22 18:47 UTC by ederign

Scaffolding of the backend. 

In this PR:
- basic Dockerfile
- basic Makefile
- Scaffold of App and first sample endpoint (http://localhost:4000/api/v1/healthcheck/)
- REST API basic infrastructure and error handling
- Basic K8s client (based on kubectl for development - check k8s.go)

2024-05-23 18:26 UTC, thesuperzapper requested changes

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/.gitignore
> +*~
This is managed by the root `.gitignore`:

```suggestion
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/.golangci.yml
> +    - unused
Not used:

```suggestion
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/README.md
> +# Workspaces backend
```suggestion
# Kubeflow Workspaces Backend
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/README.md
> +This component serves as a BFF layer for Workspaces Frontend.
```suggestion
The Kubeflow Workspaces Backend is the _backend for frontend_ (BFF) used by the Kubeflow Workspaces UI as part of [Kubeflow Notebooks 2.0](https://github.com/kubeflow/kubeflow/issues/7156).

> ⚠️ __Warning__ ⚠️
>
> The Kubeflow Workspaces Backend is a work in progress and is __NOT__ currently ready for use.
> We greatly appreciate any contributions. 
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/api/middleware.go
> +		//TODO ederign deal with preflight requests
```suggestion
		// TODO(ederign) restrict CORS to a much smaller set of trusted origins.
		// TODO(ederign) deal with preflight requests
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/go.mod
> +	github.com/julienschmidt/httprouter v1.3.0
Just checking on if this is a currently maintained package, as it last release was in 2019:

https://github.com/julienschmidt/httprouter/releases/tag/v1.3.0

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/integrations/constants.go
> +	//todo ederign -> this should come via parameter
```suggestion
	// TODO(ederign) this should come via parameter
```

2024-05-23 18:26 UTC, thesuperzapper commented on workspaces/backend/integrations/k8s.go
> +	}
Lets remove the flag for "dev" vs "production" vs "staging".

The go library provides a number of hard-coded ways to retrieve credneitals from:

- Inside Cluster: https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L41
- Outside Cluster: https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L45


I think the client auth flow should be:

1. Try default location (see https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/doc.go)
1. If that fails, assume we are in cluser and use `rest.InClusterConfig()`
2. If that fails, crash.

2024-05-29 10:50 UTC, ederign commented on workspaces/backend/go.mod
> +	github.com/julienschmidt/httprouter v1.3.0
I'm open to exploring new routers if necessary, but I'm based on this flow chart here: https://www.alexedwards.net/blog/which-go-router-should-i-use

2024-05-29 10:51 UTC, ederign commented on workspaces/backend/integrations/k8s.go
> +	}
I've removed all code and move this to another issue.

2024-05-29 10:52 UTC, jiridanek commented on workspaces/backend/go.mod
> +	github.com/julienschmidt/httprouter v1.3.0
The package does not have transitive dependencies! I think it is not very dangerous to use it https://github.com/julienschmidt/httprouter/blob/master/go.mod

2024-05-29 10:55 UTC, ederign commented
@thesuperzapper @jiridanek I've updated my PR as we discussed.

I'll open a new issue to discuss the k8 client.

2024-05-29 11:13 UTC, jiridanek commented on .gitignore
> +workspaces/backend/bin
maybe create a separate .gitignore for this in workspaces/backend?

2024-05-29 11:15 UTC, jiridanek commented on workspaces/backend/Makefile
> +	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", sub
Just fyi, make version 4.4.1 will natively support a new `--print-targets` option, which makes this solution unnecessary, if you can have new enough make

2024-05-29 11:24 UTC, jiridanek approved these changes

2024-05-29 11:43 UTC, ederign commented on .gitignore
> +workspaces/backend/bin
We had this, but @thesuperzapper asked to remove it on the last review.

2024-05-30 20:31 UTC, jiridanek commented on .gitignore
> +workspaces/backend/bin
I understand he asked to just remove the last few lines from that (because they would duplicate content of the top level .gitignore)

2024-05-31 00:44 UTC, thesuperzapper approved these changes
@ederign thanks, lets merge this and work from here!

2024-05-31 00:45 UTC, thesuperzapper commented
/lgtm

2024-05-31 00:45 UTC, merged